### ISSUE TITLE
Not catching request if host is an IP address (from within Docker container)

### ISSUE THREAD

**Issue by sandrodz** [ProxymanApp/Proxyman#1712]
## Description
When doing requests directly to an IP address proxyman is not catching requests.

## Steps to Reproduce
1. docker exec into a running container and issue command `curl http://google.com` request is logged correctly
2. issue command curl to some IP address `curl http://21.72.127.222:8089/api/operation/getPriceTypes` request is missing from proxyman

<img width="1091" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/8479569/c0a4e4a8-9f0c-4270-80e4-478ebe6c3b4d">

<img width="1523" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/8479569/d993f534-632f-46dc-af9a-8538038d5de0">

## Environment

- App version: e.g Proxyman 4.8.2
- macOS version: 13.4.1 (22F82)
- Docker version: 4.21.0 (113844)

**Comment by NghiaTranUIT** [comment]
@sandrodz Can you use `--proxy localhost:9090` in your cURL command? I guess `cURL` doesn't send the request (with IP address) to Proxyman, so Proxyman could not capture.

**Comment by sandrodz** [comment]
@NghiaTranUIT I am encountering this from within docker container.
From the local machine it works fine.

**Comment by NghiaTranUIT** [comment]
@sandrodz Have you tried to start the Docker Container within the [Automatic Script](https://docs.proxyman.io/automatic-setup/automatic-setup) Terminal ?

**Comment by NghiaTranUIT** [comment]
@sandrodz can you follow this Doc to setup the HTTP Proxy in Docker env? https://docs.docker.com/network/proxy/

**Comment by sandrodz** [comment]
@NghiaTranUIT this worked:

<img width="433" alt="image" src="https://github.com/ProxymanApp/Proxyman/assets/8479569/6bc36cc8-cf04-4a8e-b767-3b9ef329c48f">

**Comment by sandrodz** [comment]
@NghiaTranUIT this is generally a better way via docker-compose.proxyman.yml override:

```
version: '2'
services:
  php8.1-fpm-xdebug:
    environment:
      HTTP_PROXY: host.docker.internal:9090
      HTTPS_PROXY: host.docker.internal:9090
      http_proxy: host.docker.internal:9090
      https_proxy: host.docker.internal:9090
```

`docker-compose -f docker-compose.yml -f docker-compose.php8.1-fpm-xdebug.yml -f docker-compose.proxyman.yml up -d`

This is better and requires no docker daemon restart. When switching on/off.
